# deploy-flutter-app.yml
name: Reusable Flutter Deploy Solution

on:
  workflow_call:
    secrets:
      FIREBASE_SERVICE_ACCOUNT:
        required: true
      FIREBASE_APP_ID:
        required: true
    inputs:
      app-name:
        description: 'The name of the app used for the .aab file (e.g., DUMMIE-REPO)'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: self-hosted
    steps:
      - name: Download App Bundle Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-bundle

      - name: Decode Firebase Service Account
        id: decode_firebase_sa
        shell: bash
        run: |
          FIREBASE_SA_PATH="${{ runner.temp }}/firebase-sa.json"
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > $FIREBASE_SA_PATH
          echo "firebase_sa_path=$FIREBASE_SA_PATH" >> $GITHUB_OUTPUT

      - name: Upload to Firebase App Distribution
        uses: wzieba/firebas-app-distribution-action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: ${{ steps.decode_firebase_sa.outputs.firebase_sa_path }}
          file: ${{ inputs.app-name }}.aab
          groups: 'qa-testers'